spring:
  application:
    name: user-service  # Service name

  datasource:
    url: jdbc:h2:mem:testdb  # H2 in-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10  # Maximum DB connection pool size
    jpa:
      hibernate:
        ddl-auto: update  # Automatically create tables based on entities
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8082  # Service port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL (use actual Eureka IP if not running locally)
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost  # Optional: specify the hostname
    prefer-ip-address: true  # Optional: prefer IP address over hostname for service discovery

# Optional: logging and other configurations
logging:
  level:
    com.netflix.discovery: DEBUG
