spring:
  application:
    name: user-service  # Service name

  datasource:
    url: jdbc:h2:mem:testdb  # H2 in-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10  # Maximum DB connection pool size
    jpa:
      hibernate:
        ddl-auto: update  # Automatically create tables based on entities
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect

  # Ensure you are not disabling Spring Cloud Config unless you need it
  cloud:
    config:
      enabled: false  # Remove this line if you're not using Spring Cloud Config

server:
  port: 8082  # Service port for the user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL (use actual Eureka IP if not running locally)
    fetch-registry: true  # Whether to fetch the registry from Eureka
    register-with-eureka: true  # Whether to register with Eureka server
  instance:
    hostname: localhost  # Optional: specify the hostname if necessary
    prefer-ip-address: true  # Prefer IP address over hostname for service discovery

