spring:
  application:
    name: gateway  # Service name
  cloud:
    gateway:
          routes:
            - id: user-service
              uri: lb://user-service  # Eureka load balancing
              predicates:
                - Path=/user/**  # Route all requests to /user/** to the user service
            # Add more services here if needed

server:
  port: 8083  # Service port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost  # Optional: specify the hostname
    prefer-ip-address: true  # Optional: prefer IP address over hostname for service discovery

